# Generated by Django 3.0.7 on 2020-06-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('OC', 'Oczekujacy'), ('AC', 'Zaakceptowany'), ('RE', 'Odrzucony')], default='OC', max_length=20),
        ),
    ]
